### ISSUE TITLE
Implement Page views

### ISSUE THREAD

**Issue by jrob8577** [GuildCrafts/floworky#16]
As a user, I want to be able to save a specific page, so that I can return to that page immediately later.

**Comment by Moniarchy** [comment]
@EthanJStark and myself

**Comment by rachel-ftw** [comment]
Page Views: http://screencast.com/t/bhf6WQzs
- As a user I can click on a title and it will be displayed on an individual page with breadcrumb navigation at the top to keep me oriented.
- As a user I can save any individual page so I can easily return to it.

**Comment by EthanJStark** [comment]
Per our conversation yesterday, @jrob8577, I'll be interpreting this issue as "Implement starred-pages routes and database migration" unless I hear otherwise from you. As far as the front-end is concerned, @rachel-ftw has a branch from last week that has the front-end styling for this: 
https://github.com/rachel-ftw/floworky/tree/starred-styling

**Comment by EthanJStark** [comment]
@boyaohrbc and I will work on this one!
